apiVersion: v1
kind: Service
metadata:
  name: connection-group-app-service
spec:
  selector:
    app: connection-group-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
